In [1]:
%pip install pandas numpy lxml

Requirement already satisfied: pandas in c:\users\leepinpin\downloads\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\leepinpin\downloads\anaconda\lib\site-packages (2.3.5)
Requirement already satisfied: lxml in c:\users\leepinpin\downloads\anaconda\lib\site-packages (5.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\leepinpin\downloads\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\leepinpin\downloads\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\leepinpin\downloads\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\leepinpin\downloads\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

In [3]:
URL = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

In [4]:
tables = pd.read_html(URL)
df = tables[3]
#check if the table is the right one
len(tables) #check how many table did I get

8

In [5]:
tables[3].head()
df.columns = range(df.shape[1])
df = df[[0, 2]]
df = df.iloc[1:11, : ]
df.columns = ['Country', 'GDP(USD)']
df

           Country  GDP(USD)
1    United States  26854599
2            China  19373586
3            Japan   4409738
4          Germany   4308854
5            India   3736882
6   United Kingdom   3158938
7           France   2923489
8            Italy   2169745
9           Canada   2089672
10          Brazil   2081235

In [6]:
# Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method.
df['GDP(USD)'] = df['GDP(USD)'].astype(int)
# Convert the GDP value in Million USD to Billion USD
df['GDP(USD)'] = df['GDP(USD)']/1000
# Use numpy.round() method to round the value to 2 decimal places.
df['GDP(USD)'] = np.round(df['GDP(USD)'], 2)
# Rename the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'
df = df.rename(columns={'GDP(USD)': 'GDP (Billion USD)'})
df

           Country  GDP (Billion USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [7]:
# Load the DataFrame to the CSV file named "Largest_economies.csv"
df.to_csv('./Largest_economies.csv')